// <auto-generated />
using System;
using MarcasAutosApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace MarcasAutosApi.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250508203020_AddMarcaAutoMigration")]
    partial class AddMarcaAutoMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("MarcasAutosApi.Models.MarcaAuto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("FoundedYear")
                        .HasColumnType("integer");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("MarcaAuto");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Country = "United States",
                            Created = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoundedYear = 1903,
                            ImageUrl = "https://www.ford.es/content/dam/guxeu/global-shared/header/ford_oval_blue_logo.svg",
                            IsActive = true,
                            Name = "Ford",
                            Updated = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 2,
                            Country = "Germany",
                            Created = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoundedYear = 1916,
                            ImageUrl = "https://www.bmw.com/etc.clientlibs/settings/wcm/designs/bmwcom/base/resources/ci2020/img/logo-bmw-com-gray.svg",
                            IsActive = true,
                            Name = "BMW",
                            Updated = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            Id = 3,
                            Country = "Japan",
                            Created = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc),
                            FoundedYear = 1920,
                            ImageUrl = "https://dealerinspire-shared-assets.s3.amazonaws.com/public/logos/mazda/mazda-dark-no-space-desktop-logo.png",
                            IsActive = true,
                            Name = "Mazda",
                            Updated = new DateTime(2025, 5, 8, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
